<?php

/**
 * Implements hook_permission().
 */
function mconnect_permission() {
  return array(
    'mconnect client' =>  array(
      'title' => t('Mconnect client'),
      'description' => t('Perform client tasks for mconnect.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function mconnect_menu() {

  $items['user/%user/integrations'] = array(
    'title' => 'Integrations',
    'page callback' => 'light_misc_integrations',
    'page arguments' => array(1),
    'access arguments' => array('Mconnect client'),
    'type' => MENU_LOCAL_TASK
  );

  return $items;
}

/**
 * Adding feed row to DB `mconnect_data`.
 */
function mconnect_data_push($data){
  $table  = "feed_data";
  $record = (array) $data;
  drupal_write_record ($table, $record);
}

/**
 * Adding feed tag row to DB `mconnect_tag`.
 */
function mconnect_tag_push($data){
  $table  = "feed_tag";
  $record = (array) $data;
  drupal_write_record ($table, $record);
}

/**
 * Implements hook_views_api().
 */
function mconnect_views_api()
{
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'mconnect') . '/includes/views',
  );
}

